### ISSUE TITLE
Request 1st block on the chain

### ISSUE THREAD

**Issue by TheDevMinerTV** [turtlecoin/turtlecoin-rpc-js#9]
Hi there!

I want to get the hash of the 1st block of the blockchain to create a checkpoints file.
See my code [**here**](https://github.com/TheDevMinerTV/Checkpoint-Generator/blob/master/checkpoint_generator.js#L41).

It always errors out because it can't find the block 0 in the csv file.
When I try to request block 0 I get a
```
Getting block info for height 0
(node:10501) UnhandledPromiseRejectionWarning: Error: must specify height
    at Promise (/home/tobias/development/JavaScript/checkpoint-gen/node_modules/turtlecoin-rpc/lib/turtlecoind-rpc.js:87:37)
    at new Promise (<anonymous>)
    at TurtleCoindRPC.getBlockHash (/home/tobias/development/JavaScript/checkpoint-gen/node_modules/turtlecoin-rpc/lib/turtlecoind-rpc.js:85:10)
    at daemon.getBlockCount.then (/home/tobias/development/JavaScript/checkpoint-gen/checkpoint_generator.js:41:57)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:10501) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:10501) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Does somebody know how to fix this issue?

Best regards,
TheDevMinerTV

**Comment by TheDevMinerTV** [comment]
Does even somebody care if I open issues here?

**Comment by brandonlehmann** [comment]
Handle the promise rejection first.

**Comment by TheDevMinerTV** [comment]
Okay.

**Comment by TheDevMinerTV** [comment]
Done!
What next?

**Comment by brandonlehmann** [comment]
Install v0.14.1; however, be warned, there's an off-by-one error whereby you'll get a rejection anyways requesting block 0 because it doesn't exist. Request block 1.

**Comment by TheDevMinerTV** [comment]
Okay, thanks!
